bot:
 public_key: "40cb884282ec0be554b591ff7304155f5b200e4a85d624f03486bb94f9a821ce"
 id: "886046032616624138"
 devs: 
  - "Shut!#5230"
  - "Weariful#6650"
 dev_ids:
  - "470976775145390082"
  - "343778106340802580"
 logs:
  channel:
   id: "886398255540367412"